plugins {
    id 'com.gradleup.shadow' version '8.3.8'
    id 'io.papermc.paperweight.userdev'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    disableAutoTargetJvm()
}

dependencies {
    implementation "me.lucko:spark-common:${project.baseVersion}-SNAPSHOT"
    implementation(project(':spark-folia:spark-folia-12111-compat')) {
        transitive = false
    }
    paperweight.foliaDevBundle("26.2.build.6-beta")
}

repositories {
    maven { url "https://repo.papermc.io/repository/maven-public/" }
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        expand (
                'pluginVersion': project.pluginVersion,
                'pluginDescription': project.pluginDescription
        )
        include 'plugin.yml'
    }
}

shadowJar {
    archiveFileName = "spark-${project.baseVersion}-build${project.extraVersion}-folia.jar"

    dependencies {
        exclude(dependency('net.kyori:^(?!adventure-text-feature-pagination).+$'))
    }

    relocate 'net.kyori.adventure.text.feature.pagination', 'me.lucko.spark.lib.adventure.pagination'
    relocate 'net.bytebuddy', 'me.lucko.spark.lib.bytebuddy'
    relocate 'com.google.protobuf', 'me.lucko.spark.lib.protobuf'
    relocate 'org.objectweb.asm', 'me.lucko.spark.lib.asm'
    relocate 'one.profiler', 'me.lucko.spark.lib.asyncprofiler'
    relocate 'me.lucko.bytesocks.client', 'me.lucko.spark.lib.bytesocks'
    relocate 'org.java_websocket', 'me.lucko.spark.lib.bytesocks.ws'

    project.applyExcludes(delegate)
}

artifacts {
    archives shadowJar
    shadow shadowJar
}
